FROM mysql:5.7.19

MAINTAINER Raylison Nunes <raylison100@gmail.com>

# RUN   /etc/init.d/mysql start
# RUN   mysql -u root CREATE USER 'admin'@'localhost' IDENTIFIED BY '99291072'; 
# RUN   mysql -u root grant all privileges on *.* to 'admin'@'localhost'; 
# RUN   mysql -u root FLUSH PRIVILEGES;
# RUN   mysql -u root CREATE DATABASE instamanager;
      
CMD ["mysqld"]

EXPOSE 3306